### ISSUE TITLE
Do you plan to implement error handling?

### ISSUE THREAD

**Issue by syuilo** [pushrocks/gulp-browser#2]
unused variable!
https://github.com/pushrocks/gulp-browser/blob/master/index.js#L7
sorry my English

**Comment by philkunz** [comment]
@syuilo Hi! Yes I'll implement it asap. See #1 : It is already on my roadmap. I wish you a good start into this new week, and by the end of it this issue will have been addressed. :)

**Comment by philkunz** [comment]
#1

**Comment by philkunz** [comment]
#1
