### ISSUE TITLE
What would be causing this error?

### ISSUE THREAD

**Issue by KingScooty** [pushrocks/gulp-browser#4]
I came across this plugin when trying to figure out why `browserify` and `vinyl-transform` were causing errors on a project i'd not touched in a few months.

I seem to be getting the following error using `gulp-browser`, and i'm wondering what might be causing it:

```shell
/node_modules/vinyl-fs/node_modules/vinyl/index.js:143
      throw new Error('File.contents can only be a Buffer, a Stream, or null.');
      ^

Error: File.contents can only be a Buffer, a Stream, or null.
```

My JS task looks like:

```javascript
gulp.task('js-compile',function() {
  var stream = gulp.src('./assets/_js/main.js')
    .pipe(gulpBrowser.browserify())
    .pipe(uglify())
    .pipe(gulp.dest("./assets/javascripts/"));
  return stream;
});
```

**Comment by philkunz** [comment]
@KingScooty Hi, and thanks for using gulp-browser.
I have to improve this plugin a bit to better handle errors. This error looks like the case where gulpBrowser fails due to the **npm modules that you are going to browserify not being within the path of the file `'./assets/_js/main.js'`**

To fix it, make sure that all npm modules are available from a `node_modules` folder on the same or higher folder level relative to `'./assets/_js/main.js'`

Cheers Phil

**Comment by KingScooty** [comment]
A-ha, i thought that would be the case. One of the files i'm requiring inside `./assets/_js/main.js` is actually a file i installed via `bower`, and it's located at `./assets/bower_components/pjax/src/pjax`. Would that be causing it?

All the other references are to either npm modules at `./node_modules`, or js files in `./assets/_js/`.

**Comment by KingScooty** [comment]
So i've stripped all the requires away, to see where the error is coming from. 

It pulls in files from `node_modules` just fine, but anything relative to `./assets/_js/main` seems to throw an error.

```javascript
//main.js
var isVisible = require('./tools/is-visible');
```

^^ this fails. The path is correct.

**Comment by philkunz** [comment]
I think the problem you have is with the way `gulp.src` works and the values it creates file.path file.base ...

Do I get this right about your structure:

We are in "."
"./assets/_js/main" is the file you browserify
"./tools/is-visible" is the file you require
"." in the above represents the same directory

you require the second file in the first one as "./tools/is-visible.js"?

try the following:
```javascript
var isVisible = require('../../../tools/is-visible');
```

**Comment by philkunz** [comment]
try v0.0.16 for more insights.

Also, I'll be releasing a new plugin called gulp-inspect tonight, which posts nice information about your file object to console.

Have a nice evening.
Phil

**Comment by KingScooty** [comment]
Ah yeah, so it looks like `gulp-browser` wants all the non npm modules required via the path *relative* to the `gulpfile`.

```javascript
var isVisible = require('./assets/_js/tools/is-visible');
```

Works. Which is a little frustrating, as i'd prefer it to be relative to `main.js` mentioned as the src in the gulpfile.
