### ISSUE TITLE
Empty JS files causes browserify() to throw exception

### ISSUE THREAD

**Issue by anyweez** [pushrocks/gulp-browser#48]
https://github.com/anyweez/gulp-browserify-emptyjs for sample repo

If the input file(s) have no content, gulp-browser crashes in a pretty cryptic way. Seems like at least maybe a more user-friendly error message would be nice, or ideally browserify() would still run and just emit an empty js file. What do you think? Happy to investigate an improvement if you're open to it.

```
Error:  gulp-browser: .browserify() Cannot find module '/Users/home/gulp-browserify-emptyjs/js/_stream_0.js' from '/Users/home/gulp-browserify-emptyjs/js/'
```

cc @kholliday88 and @wheatbrad who originally discovered the issue

**Comment by anyweez** [comment]
I know [gulp-browserify](https://www.npmjs.com/package/gulp-browserify) isn't maintained but the default behavior in their case is to output an empty JS file.

**Comment by philkunz** [comment]
Hi, I'll take a look tomorrow, and if I can reproduce the problem I'll implement a fix.
Empty JS files shoud not pose a problem.

Cheers
Phil from Lossless

**Comment by philkunz** [comment]
I'm extending the tests to cover the node versions:

* LTS
* STABLE

.browserify() will be tested for:

* normal js file requiring existent module -> expects no error
* normal js file requiring nonexistent module -> expects error
* malformed js file -> expects error
* empty js file -> expects no error, but warning in console

Cool?

**Comment by anyweez** [comment]
👍  sounds great. thank you!

**Comment by philkunz** [comment]
version 1.2.0 should publish on npm any minute given that tests run through on travis.
Have a nice day!

**Comment by philkunz** [comment]
... published!
see build log here: https://travis-ci.org/pushrocks/gulp-browser/builds/120073139

**Comment by anyweez** [comment]
Confirmed to have fixed the issue -- thanks for the fast turnaround @philkunz!
